import { Story, Meta } from '@storybook/react/types-6-0';
import { ButtonProps } from './Button';
declare const _default: Meta<import("@storybook/react/types-6-0").Args>;
export default _default;
export declare const EaseInBack: Story<ButtonProps>;
export declare const EaseInCirc: Story<ButtonProps>;
export declare const EaseInCubic: Story<ButtonProps>;
export declare const EaseInExpo: Story<ButtonProps>;
export declare const EaseInOutBack: Story<ButtonProps>;
export declare const EaseInOutCirc: Story<ButtonProps>;
export declare const EaseInOutCubic: Story<ButtonProps>;
export declare const EaseInOutExpo: Story<ButtonProps>;
export declare const EaseInOutQuad: Story<ButtonProps>;
export declare const EaseInOutQuart: Story<ButtonProps>;
export declare const EaseInOutQuint: Story<ButtonProps>;
export declare const EaseInOutSine: Story<ButtonProps>;
export declare const EaseInQuad: Story<ButtonProps>;
export declare const EaseInQuart: Story<ButtonProps>;
export declare const EaseInQuint: Story<ButtonProps>;
export declare const EaseInSine: Story<ButtonProps>;
export declare const EaseOutBack: Story<ButtonProps>;
export declare const EaseOutCirc: Story<ButtonProps>;
export declare const EaseOutCubic: Story<ButtonProps>;
export declare const EaseOutExpo: Story<ButtonProps>;
export declare const EaseOutQuad: Story<ButtonProps>;
export declare const EaseOutQuart: Story<ButtonProps>;
export declare const EaseOutQuint: Story<ButtonProps>;
export declare const EaseOutSine: Story<ButtonProps>;
